#!/usr/bin/env bash

echo "+----------------------------+"
echo "| Executing tests using sbt  |"
echo "+----------------------------+"
if [[ -n "${TRAVIS_SCALA_VERSION:-}" ]]; then
  sbt "++$TRAVIS_SCALA_VERSION ; test"
else
  sbt test
fi
