name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd dataedu-fe
        docker build . --file Dockerfile -t hedayati/data-engineering-fe:latest
        docker push hedayati/data-engineering-fe:latest
